apiVersion: v1
kind: Pod
metadata:
  name: liveness
spec:
  containers:
  - image: luksa/kubia-unhealthy
    name: liveness
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 15  # Kubernates will wait 15 second to send the first probe.
