apiVersion: v1
kind: Pod
metadata:
  labels:
    run: kubia
    build: minhaz
  name : nginx-redis
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
  - image: redis
    name: redis
    ports:
    - containerPort: 8081
      protocol: TCP