apiVersion: v1
kind: Pod
metadata:
  labels:
    run: kubia
    env: production
  name : redis
  namespace: api
spec:
  containers:
  - image: redis
    name: redis
    ports:
    - containerPort: 80
      protocol: TCP