apiVersion: v1
kind: ReplicationController
metadata:
  name: server-rc
spec:
  replicas: 3

  selector:
    app: server

  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: minhaz1217/simple-dotnet
          ports:
            - containerPort: 80
