apiVersion: v1
kind: Pod
metadata:
  labels:
    service: redis
    purpose: nginx-redis
  name : redis
spec:
  containers:
  - image: redis
    name: redis
    ports:
    - containerPort: 6379
      protocol: TCP