apiVersion: v1
kind: Pod
metadata:
  labels:
    service: nginx
    purpose: nginx-redis
  name : nginx
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP