apiVersion: batch/v1
kind: Job
metadata:
  name: multi-completion-job
spec:
  completions: 5
  template: 
    metadata:
      name: multi-completion-job
    spec:
      restartPolicy: OnFailure
      containers:
      - name: main
        image: luksa/batch-job