apiVersion: batch/v1
kind: Job
metadata:
  name: time-limited-job
spec:
  activeDeadlineSeconds: 10
  backoffLimit: 3
  template: 
    metadata:
      name: time-limited-job
    spec:
      restartPolicy: OnFailure
      containers:
      - name: main
        image: luksa/batch-job