apiVersion: batch/v1
kind: CronJob
metadata:
  name: basic-cronjob
spec:
  schedule: "0,15,30,45 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: basic_cronjob
        spec:
          restartPolicy: OnFailure
          containers:
            - name: main
              image: luksa/batch-job