apiVersion: batch/v1
kind: CronJob
metadata:
  name: time-limited-cronjob
spec:
  schedule: "0,15,30,45 * * * *"
  startingDeadlineSeconds: 15
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: time-limited-cronjob
        spec:
          restartPolicy: OnFailure
          containers:
            - name: main
              image: luksa/batch-job
