apiVersion: v1
kind: ReplicationController
metadata:
  name: server1-rc
spec:
  replicas: 3

  selector:
    app: server1

  template:
    metadata:
      labels:
        app: server1
    spec:
      containers:
        - name: server1
          image: minhaz1217/simple-dotnet
          ports:
            - containerPort: 80
