apiVersion: v1
kind: ReplicationController
metadata:
  name: server2-rc
spec:
  replicas: 3
  
  selector:
    app: server2

  template:
    metadata:
      labels:
        app: server2
    spec:
      containers:
        - name: server2
          image: minhaz1217/simple-dotnet
          ports:
            - containerPort: 80
