apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dotnet-ds
spec:
  selector:
    matchLabels:
      app: dotnet
  template:
    metadata:
      labels:
        app: dotnet
    spec:
      nodeSelector:
        disk: ssd
      containers:
      - name: main
        image: minhaz1217/simple-dotnet